[package]
name = "halo-examples"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Examples demonstrating Halo and Halo2 usage"

[dependencies]
# Workspace dependencies
halo-core.workspace = true
halo-recursion.workspace = true
halo2-arith.workspace = true
commitments.workspace = true

# Core cryptographic dependencies
group.workspace = true
ff.workspace = true
pairing.workspace = true
rand.workspace = true

# Utilities
serde.workspace = true
anyhow.workspace = true
hex.workspace = true

# For examples
bls12_381.workspace = true

[[example]]
name = "scalar_multiplication_sequencer"
path = "examples/scalar_multiplication_sequencer.rs"

[[example]]
name = "comprehensive_demo"
path = "examples/comprehensive_demo.rs"