[workspace]
resolver = "2"
members = [
    "crates/field",
    "crates/commitments",
    "crates/marlin",
    "crates/sonic",
    "crates/examples",
    "crates/benchmarks",
    "crates/cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vats98754/zero-knowledge-proofs"
homepage = "https://github.com/vats98754/zero-knowledge-proofs"
documentation = "https://docs.rs/zero-knowledge-proofs"
authors = ["Zero Knowledge Proofs Contributors"]
keywords = ["cryptography", "zero-knowledge", "marlin", "sonic", "snark"]
categories = ["cryptography", "science"]

[workspace.dependencies]
# Cryptographic dependencies
ark-ff = "0.4"
ark-ec = "0.4"
ark-poly = "0.4"
ark-serialize = "0.4"
ark-std = "0.4"
ark-bls12-381 = "0.4"
ark-bn254 = "0.4"

# Utility dependencies
rand = "0.8"
rand_chacha = "0.3"
blake2 = "0.10"
sha2 = "0.10"
thiserror = "1.0"
anyhow = "1.0"
rayon = "1.7"

# Development dependencies
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.2"

# CLI dependencies
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"