[workspace]
members = [
    "crates/field",
    "crates/pc",
    "crates/plonk-arith",
    "crates/plonk-prover",
    "crates/plonk-verifier",
    "crates/examples",
    "benches",
    "cli/plonk-setup-universal",
    "cli/plonk-compile",
    "cli/plonk-prove",
    "cli/plonk-verify",
]
resolver = "2"

[workspace.dependencies]
# Arkworks ecosystem for elliptic curves and finite fields
ark-ff = { version = "0.4", features = ["asm"] }
ark-ec = { version = "0.4", features = ["parallel"] }
ark-poly = { version = "0.4", features = ["parallel"] }
ark-serialize = { version = "0.4", features = ["derive"] }
ark-std = { version = "0.4", features = ["parallel"] }
ark-bls12-381 = { version = "0.4", features = ["curve"] }
ark-poly-commit = { version = "0.4", features = ["parallel"] }

# Cryptographic utilities
rand = "0.8"
rand_chacha = "0.3"
sha3 = "0.10"

# Parallel computation
rayon = "1.7"

# Serialization
serde = { version = "1.0", features = ["derive"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# CLI utilities
clap = { version = "4.0", features = ["derive"] }

# Benchmarking
criterion = { version = "0.5", features = ["html_reports"] }

# Testing
proptest = "1.2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[profile.bench]
opt-level = 3
lto = "thin"
debug = true