[workspace]
resolver = "2"
members = [
    "crates/bulletproofs-core",
    "crates/ipa", 
    "crates/range",
    "crates/benches",
    "crates/examples",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Zero Knowledge Proofs Contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/vats98754/zero-knowledge-proofs"
homepage = "https://github.com/vats98754/zero-knowledge-proofs"

[workspace.dependencies]
# Cryptographic primitives
curve25519-dalek = { version = "4.1", features = ["serde", "rand_core"] }
merlin = "3.0"
rand = "0.8"
rand_core = { version = "0.6", default-features = false }

# Serialization
serde = { version = "1.0", features = ["derive"] }

# Error handling
thiserror = "1.0"

# Benchmarking and testing
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.0"

# Utilities
rayon = "1.7"
itertools = "0.12"

# CLI
clap = { version = "4.0", features = ["derive"] }