[package]
name = "plonk-verifier"
version = "0.1.0"
edition = "2021"
description = "PLONK verifier implementation"
license = "MIT OR Apache-2.0"

[dependencies]
plonk-field = { path = "../field" }
plonk-pc = { path = "../pc" }
plonk-arith = { path = "../plonk-arith" }
plonk-prover = { path = "../plonk-prover" }
ark-ff.workspace = true
ark-bls12-381.workspace = true
ark-std.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true