[package]
name = "setup"
version = "0.1.0"
edition = "2021"
description = "Trusted setup and SRS generation for Groth16"
license = "MIT"

[dependencies]
r1cs = { path = "../r1cs" }
qap = { path = "../qap" }
ark-bls12-381 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-std = { workspace = true }
ark-serialize = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rand_chacha = { workspace = true }
proptest = { workspace = true }