[package]
name = "zkvm-core"
version = "0.1.0"
edition = "2021"
description = "Core zkVM implementation with execution trace generation"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }