[package]
name = "qap"
version = "0.1.0"
edition = "2021"
description = "Quadratic Arithmetic Program (QAP) conversion and evaluation"
license = "MIT"

[dependencies]
r1cs = { path = "../r1cs" }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-std = { workspace = true }
ark-serialize = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ark-bls12-381 = { workspace = true }
proptest = { workspace = true }